language: node_js
node_js:
  - "node"

# Cache seems to be causing issues with `npm ci`
# cache:
#   directories:
#     - node_modules

env:
  - NODE_DEBUG=gh-pages

deploy:
  - skip_cleanup: true
    provider: script
    script: npm run deploy
    on:
      branch: master
